### ISSUE TITLE
Violation non-passive event listener on 'touchstart' event

### ISSUE THREAD

**Issue by karjanme** [SaschaIoT/HttpWebcamLiveStream#2]
Running this in Chrome gives the following violation notice:

Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

**Comment by SaschaIoT** [comment]
Thanks. I marked the touchstart event handler as passive.
